version: '3'
services:
  app: 
    container_name: geo1-Hen-Nie
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: geo1-mongo-Hen-Nie
    restart: always
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data
    
